### ISSUE TITLE
UI submodule expects default security group to be present

### ISSUE THREAD

**Issue by benchoncy** [outerbounds/terraform-aws-metaflow#27]
The UI submodule assumes the AWS default security group is present.

I receive the following error when using the UI submodule.
```
Error: no matching SecurityGroup found

  with module.metaflow_ui.data.aws_security_group.vpc_default,
  on .terraform/modules/metaflow_ui/modules/ui/data.tf line 5, in data "aws_security_group" "vpc_default":
   5: data "aws_security_group" "vpc_default" {
```
ui/data.tf line 5:
```
data "aws_security_group" "vpc_default" {
  name   = "default"
  vpc_id = var.metaflow_vpc_id
}
```

I believe the module should create its own security group rather than expect the AWS default to exist.

**Comment by benchoncy** [comment]
It appears this is never used anywhere in the terraform. I will open a PR to remove this as it is not used.

**Comment by oavdeev** [comment]
Makes sense, we should remove those references to default security groups throughout all modules really.

**Comment by benchoncy** [comment]
> Makes sense, we should remove those references to default security groups throughout all modules really.

This reference in the UI submodule appears to be the only remaining reference from what I see.
