### ISSUE TITLE
compute environment for gpu

### ISSUE THREAD

**Issue by MarselScheer** [outerbounds/terraform-aws-metaflow#29]
I used the module (v0.5.0 and master) to deploy the infrastructure (thanks for this great module!). But my impression is that currently I cannot use @batch(gpu=1) for a step. The corresponding task gets stuck in runnable. Metaflow instantiates a p2-instance if i request it but the tasks with @batch(gpu=1) never leaves the state runnable. (Note that when i terminate that task manually, then other "pure cpu-tasks", i.e. not decorated with @batch(gpu=1), get executed on that p2-instance)
My best guess so far is that the terraform module simply does not create a gpu compute environment. There is a very old commit 91a8f26 in this repo but the gpu related parts disappeared two commits later and now only one cpu-ami and cpu-compute-environment is created.

Are there any plans to integrate gpu compute environments back into the module? Or is there an obvious way to enable gpu compute environment i missed?

**Comment by MarselScheer** [comment]
Changing "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended" in modules/computation/data.tf to "/aws/service/ecs/optimized-ami/amazon-linux-2/gpu/recommended" works, i.e. a p2-instance is started, torch.cuda.device_count() returns 1 and nvidia-smi also returns the expected output. 

I have no idea what the full implications of this change is. At least regular dummy-cpu-tasks are executed on c4-instance. On the surface, it looks like it serves the purpose for my personal use.

However, my gut feeling tells me that this is a bad solution :-)

**Comment by MarselScheer** [comment]
Just did another experiment by replacing the image in the batch-decorator with "763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04" and now the tensor can be placed on the gpu: 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   30C    P0    72W / 149W |      3MiB / 11441MiB |     54%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
tensor([[0.7153, 0.1191, 0.5467],
        [0.8921, 0.7313, 0.6024]])
tensor([[0.8088, 0.7170, 0.1789],
        [0.7452, 0.6927, 0.6914]], device='cuda:0')
```
Any idea why it is working now? What I find  confusing is that the output of nvidia-smi states cuda-version 11.4 and not 10.1?!?

(BTW: Also just to double check I use the image that I used yesterday, I again see the error.)

**Comment by oavdeev** [comment]
Good call, let me try to reproduce. I think we may even be able to omit `image_id` there and let Batch choose the right one. In the meantime, if you haven't yet, feel free to open a thread in our slack http://slack.outerbounds.co/ . I know for sure there are at least a few folks using Metaflow with GPUs on Batch.

**Comment by oavdeev** [comment]
More findings:
1. Re: image id, just omitting it works https://github.com/outerbounds/terraform-aws-metaflow/pull/30 . I'll merge this after a bit more testing
2. CUDA version: it seems like its expected and `nvidia-smi` would report the version of the CUDA runtime from the host. The documentation on this is a little confusing, see [this StackOverflow answer](https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi).
3. The exact combination of AMI and docker image you tried and got a CUDA error works fine for me with p3 instances, I can create tensors on CUDA device. So I'm suspecting its some kind of bug with CUDA either baked in the docker image or the host. May be worth contacting AWS support for that. Some comments on SO seem to suggest that it is safe(r) to use an older CUDA toolkit with a newer (host) runtime, but the official doc seems to imply that it should be fine either way with CUDA 11.x

**Comment by oavdeev** [comment]
Great! Please let us know if you run into anything else, I'm going to close this one for now
