### ISSUE TITLE
RDS database T2 instance is being retired

### ISSUE THREAD

**Issue by elgehelge** [outerbounds/terraform-aws-metaflow#68]
[Just a service message]

The current default RDS instance for the metadata service is:
https://github.com/outerbounds/terraform-aws-metaflow/blob/fd5b56e1a6644e573385324ad0110f5e1441fbc6/modules/datastore/variables.tf#L4

However, this instance will soon not be available.

AWS wrote this to me (shortened):

_You are receiving this notification because you have one or more Amazon RDS for PostgreSQL database instances running on db.m4, db.r4, or db.t2 instance types. We plan to retire all M4, R4, and T2 instances by April 2024. [...] **Reserved instances for db.m4, db.r4, and db.t2 will no longer be available for purchase beginning on June 30, 2023.**_

_**Depending on the instance type you choose to upgrade to, you may also need to upgrade your PostgreSQL database version. We recommend that you upgrade your database engine to PostgreSQL 13.4 or higher.** For more details on supported RDS DB instance classes for each engine version please refer to the Amazon RDS user guide._

**Comment by ryewilson** [comment]
I created this PR to fix it: https://github.com/outerbounds/terraform-aws-metaflow/pull/72
